[package]
name = "quic"
version = "0.1.0"
authors = ["cssivision <cssivision@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "1"
thiserror = "1"
rustls = { version = "0.20", features = ["quic"] }
tinyvec = { version = "1.5", features = ["alloc"] }
