[package]
name = "quic"
version = "0.1.0"
authors = ["cssivision <cssivision@gmail.com>"]
edition = "2018"

[dependencies]
quiche = "0.6"
tokio = { version = "0.3", features = ["full"] }
bytes = "0.5"
ring = "0.16"

[dev-dependencies]
tokio = { version = "0.3", features = ["full"] }
